# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

services:
  redis: 
    image: redis
    ports:
    - 6379/tcp

variables:
  buildConfiguration: 'Release'

steps:
- script: 
- script: dotnet restore
- script: dotnet build --configuration $(buildConfiguration)
- script: dotnet test TestProject --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'